Repository jupyter/notebook, pull requests merged in 2018-04, with the labels that each got.

#3004 Add shutdown button option
  notebook/notebookapp.py
  notebook/static/base/less/page.less
  notebook/static/tree/js/main.js
  notebook/static/tree/js/shutdownbutton.js
  notebook/templates/tree.html
  notebook/tree/handlers.py
Labels: component:Notebook, component:Server, type:Enhancement

#3497 Prevent default event handling on new terminal
  notebook/static/tree/js/terminallist.js
Labels: component:File Browser, type:Bug

#3525 add tips
  docs/source/extending/frontend_extensions.rst
Labels: tag:Documentation
