Repository jupyter/notebook, pull requests merged in 2019-06, with the labels that each got.

#4661 Add id for command palette button group
  notebook/static/notebook/js/maintoolbar.js
Labels: component:Notebook

#4674 bugfix: shutdown_server returns True when pid exists
  notebook/notebookapp.py
Labels: component:Server, type:Bug

#4703 Solved issue 3957
  notebook/templates/tree.html
Labels: tag:Accessibility

#4686 Solved Issue #3941
  notebook/static/tree/js/notebooklist.js
Labels: tag:Accessibility

#4693 Solved Issue #3996
  notebook/static/notebook/js/notificationarea.js
Labels: tag:Accessibility

#4691 Solved Issue #3973
  notebook/templates/tree.html
Labels: tag:Accessibility

#4685 Solved Issue #3938
  notebook/static/notebook/js/maintoolbar.js
Labels: tag:Accessibility

#4689 Solved Issue #3970
  notebook/templates/tree.html
Labels: tag:Accessibility

#4695 Solved Issues #3963 and #3960
  notebook/static/tree/js/newnotebook.js
  notebook/templates/tree.html
Labels: tag:Accessibility

#4711 Solved Issue #4006
  notebook/static/base/js/dialog.js
  notebook/static/notebook/js/celltoolbarpresets/default.js
Labels: tag:Accessibility

#4677 Solved Issues #4015 and #3951
  notebook/static/base/js/dialog.js
Labels: tag:Accessibility

#4696 Solved issue #4009
  notebook/static/tree/js/main.js
  notebook/templates/tree.html
Labels: tag:Accessibility

#4718 Solved Issue #3967: added more descriptive title for tree page
  notebook/tree/handlers.py
Labels: tag:Accessibility

#4719 Add title for link to root folder
  notebook/static/tree/js/notebooklist.js
Labels: tag:Accessibility

#4690 Solved issues #3998, #3971 and #3968
  notebook/templates/notebook.html
  notebook/templates/tree.html
Labels: tag:Accessibility

#4688 Solved Issue #3961
  notebook/static/tree/js/notebooklist.js
Labels: tag:Accessibility

#4726 Switch from preact to react
  bower.json
  notebook/static/notebook/js/shortcuteditor.js
  notebook/templates/page.html
  package.json
  setupbase.py
Labels: type:Maintenance
