Repository jupyter/notebook, pull requests merged in 2020-05, with the labels that each got.

#5433 Add release instructions
  RELEASE.md
  docs/source/development_release.rst
  docs/source/index.rst
Labels: tag:Documentation, type:Enhancement

#5455 Convert notifications JS test to selenium
  notebook/tests/notebook/notifications.js
  notebook/tests/selenium/test_notifications.py
  notebook/tests/selenium/utils.py
Labels: component:Notebook

#5231 Add Japanese document
  docs-translations/ja-JP/README.md
  docs-translations/ja-JP/resources/Notebook_Editor.GIF
  docs-translations/ja-JP/resources/dashboard.GIF
  docs-translations/ja-JP/resources/edit_mode.GIF
  docs-translations/ja-JP/resources/file_editor.GIF
  docs-translations/ja-JP/resources/running_code_med.png
Labels: tag:Documentation

#5158 Migrate Move multiselection test to selenium
  notebook/tests/notebook/move_multiselection.js
  notebook/tests/selenium/test_move_multiselection.py
  notebook/tests/selenium/test_multiselect_toggle.py
Labels: tag:Testing

#5296 Make a notebook writable after successful save-as
  notebook/static/notebook/js/notebook.js
  notebook/tests/selenium/test_save_readonly_as.py
Labels: component:Notebook

#4738 Add actual watch script
  package.json
Labels: component:Server, type:Maintenance

#4795 added `--autoreload` flag to `NotebookApp`
  .gitignore
  notebook/notebookapp.py
Labels: component:Server

#5484 Added functionality to allow filter kernels by Jupyter Enterprise Gat…
  notebook/gateway/managers.py
Labels: status:Waiting for Author

#2922 'Play' icon for run-cell toolbar button
  docs/source/examples/Notebook/Notebook Basics.ipynb
  docs/source/examples/Notebook/Running Code.ipynb
  notebook/static/notebook/js/actions.js
Labels: component:Notebook, status:Needs Discussion, tag:Design and UX
