Repository jupyter/notebook, pull requests merged in 2020-06, with the labels that each got.

#5516 Backspace deletes empty line (#5502)
  notebook/static/notebook/js/codecell.js
Labels: component:Notebook

#4732 Solve issue #3940: The dropdown submenu at notebook page is not keyboard accessible
  notebook/static/acc_overwrite.less
  notebook/static/notebook/js/main.js
  notebook/static/notebook/js/menubar.js
  notebook/static/notebook/less/menubar.less
  notebook/templates/notebook.html
Labels: tag:Accessibility

#4729 Tooltips visible through keyboard navigation for specified buttons: issue #3964
  notebook/static/tree/less/tree.less
  notebook/templates/tree.html
Labels: tag:Accessibility

#4670 Fix for recursive symlink issue #4669
  notebook/services/contents/filemanager.py
  notebook/services/contents/tests/test_manager.py
Labels: component:Server

#4180 Fix for the terminal shutdown issue
  notebook/terminal/handlers.py
Labels: component:Terminal
