Repository jupyter/notebook, pull requests merged in 2021-03, with the labels that each got.

#6010 Add square logo and desktop entry files
  jupyter-notebook.desktop
  jupyter.svg
  notebook.svg
  setup.py
Labels: type:Enhancement

#6014 Add changelog entry for 6.3 release
  CHANGELOG.md
Labels: tag:Documentation

#6020 Fix readthedocs environment
  docs/environment.yml
Labels: tag:Documentation

#6021 Fixes related to the recent changes in the documentation
  MANIFEST.in
  setup.py
Labels: tag:Documentation, type:Maintenance

#6017 Fix: split_cell doesn't always split cell
  notebook/static/notebook/js/cell.js
Labels: component:Notebook, type:Bug

#6025 Minor typographical and comment changes
  notebook/static/notebook/js/notebook.js
Labels: tag:Documentation
