Repository jupyter/notebook, pull requests merged in 2021-08, with the labels that each got.

#6122 Add missing file to manifest
  MANIFEST.in
  RELEASE.md
  pyproject.toml
Labels: bug

#6125 Automated Changelog Entry for 6.4.2 on master
  CHANGELOG.md
Labels: documentation

#6130 Clean up link checking
  .github/workflows/check-release.yml
  notebook/tests/README.md
  pyproject.toml
Labels: maintenance

#6135 Automated Changelog Entry for 6.4.3 on master
  CHANGELOG.md
Labels: documentation

#6152 Update Manual Release Instructions
  RELEASE.md
Labels: documentation
