Repository jupyter/notebook, pull requests merged in 2021-04, with the labels that each got.

#6030 Fix Handling of Encoded Paths in Save As Dialog
  notebook/static/notebook/js/notebook.js
Labels: component:Notebook, type:Bug

#6042 Add Workflow Permissions for Lock Bot
  .github/workflows/lock.yml
Labels: type:Maintenance

#6045 Spelling correction
  docs/source/examples/Notebook/Working With Markdown Cells.ipynb
Labels: tag:Documentation
