Repository jupyter/notebook, pull requests merged in 2021-05, with the labels that each got.

#6052 Revert "do not apply asyncio patch for tornado >=6.1"
  notebook/notebookapp.py
Labels: maintenance

#6048 Use Jupyter Releaser
  .github/workflows/check-release.yml
  .gitignore
  CHANGELOG.md
  MANIFEST.in
  RELEASE.md
  docs/source/config_overview.rst
  docs/source/examples/Notebook/Distributing Jupyter Extensions as Python Packages.ipynb
  docs/source/examples/Notebook/header.md
  docs/source/notebook.rst
  notebook/_version.py
  notebook/static/base/js/namespace.js
  package.json
  pyproject.toml
  setup.py
  tools/tests/CSS Reference.ipynb
Labels: maintenance

#6058 Automated Changelog Entry for 6.4.0rc0 on master
  CHANGELOG.md
Labels: documentation

#6061 Bind the HTTPServer in start
  notebook/notebookapp.py
Labels: bug

#6059 Automated Changelog Entry for 6.4.0 on master
  CHANGELOG.md
Labels: documentation

#6070 "#element".tooltip is not a function on home page fixed.
  notebook/templates/tree.html
Labels: bug
