Repository jupyter/notebook, pull requests merged in 2022-08, with the labels that each got.

#6497 Update versioning mechanism and pin jupyter_client<7
  notebook/_version.py
  setup.py
Labels: bug

#6499 Pin `ypy-websocket` to `0.2`
  .github/actions/build-dist/action.yml
  .github/workflows/buildutils.yml
  pyproject.toml
Labels: maintenance

#6502 Update changelog for 5.7.14a0 release
  docs/source/changelog.rst
Labels: documentation

#6505 Uninstall `nbclassic` on Binder so Notebook v7 can load
  binder/postBuild
Labels: maintenance

#6506 Adding jupyterlab-probot yml file for labeling new issues
  .github/jupyterlab-probot.yml
Labels: maintenance

#6520 Update reference snapshots
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-save-and-export-notebook-as…-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-save-and-export-notebook-as…-firefox-linux.png
Labels: maintenance

#6518 Add Gitpod files
  .gitpod.yml
Labels: maintenance

#6522 Using group method to match regex items
  notebook/_version.py
Labels: bug

#6523 Troubleshoot failing `macos` check on CI
  .github/workflows/build.yml
  .github/workflows/buildutils.yml
Labels: maintenance

#6527 Add task to auto activate the dev environment on Gitpod
  .gitpod.yml
Labels: maintenance

#6530 Automated Changelog Entry for 6.5.0rc0 on 6.5.x
  CHANGELOG.md
Labels: documentation
