Repository jupyter/notebook, pull requests merged in 2022-12, with the labels that each got.

#6609 Fix rename_file to handle relative paths properly (related to GHSA-v7vq-3x77-87vg?)
  notebook/services/contents/filemanager.py
  notebook/services/contents/tests/test_manager.py
Labels: bug

#6658 Adopt ruff and typing
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/dependabot.yml
  .github/workflows/build.yml
  .pre-commit-config.yaml
  .prettierignore
  README.md
  binder/example.ipynb
  buildutils/src/release-bump.ts
  docs/source/conf.py
  docs/source/examples/Notebook/Importing Notebooks.ipynb
  docs/source/examples/Notebook/Running Code.ipynb
  notebook/app.py
  notebook/py.test
  pyproject.toml
  tests/conftest.py
  tests/test_app.py
  ui-tests/test/jupyter_server_config.py
  ui-tests/test/notebook.spec.ts
Labels: maintenance

#6660 Apply PR #6609 to 6.5.x (Fix rename_file and delete_file to handle hidden files properly)
  notebook/services/contents/filemanager.py
  notebook/services/contents/tests/test_manager.py
Labels: bug

#6667 CI Cleanup
  .github/workflows/build.yml
  .github/workflows/ui-tests.yml
  .pre-commit-config.yaml
  pyproject.toml
  ui-tests/test/jupyter_server_config.py
Labels: maintenance

#6668 Add sys_info to page template for 6.5.x
  notebook/templates/page.html
Labels: enhancement

#6669 Add spelling and docstring enforcement
  .github/workflows/build.yml
  .pre-commit-config.yaml
  docs/source/conf.py
  notebook/__main__.py
  notebook/_version.py
  notebook/app.py
  pyproject.toml
Labels: maintenance
