Repository jupyter/notebook, pull requests merged in 2022-10, with the labels that each got.

#6550 Fix: No mouse pointer when hovering on the Jupyter icon
  packages/application-extension/src/index.ts
Labels: bug

#6551 Automated Changelog Entry for 7.0.0a6 on main
  CHANGELOG.md
Labels: documentation

#6487 Left right panel in Notebook view
  app/index.js
  app/package.json
  packages/application-extension/src/index.ts
  packages/application-extension/src/sidebarpalette.ts
  packages/application/src/app.ts
  packages/application/src/shell.ts
  packages/application/style/index.css
  packages/application/style/index.js
  packages/application/style/sidepanel.css
  packages/application/test/shell.spec.ts
  packages/notebook-extension/src/index.ts
  ui-tests/test/general.spec.ts
  ui-tests/test/general.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/general.spec.ts-snapshots/notebook-firefox-linux.png
  ui-tests/test/menus.spec.ts
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-edit-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-kernel-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-kernel-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-firefox-linux.png
  ui-tests/test/mobile.spec.ts
  ui-tests/test/mobile.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-firefox-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/tree-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/tree-firefox-linux.png
  ui-tests/test/notebook.spec.ts
  ui-tests/test/notebook.spec.ts-snapshots/notebooktools-right-panel-chromium-linux.png
  ui-tests/test/notebook.spec.ts-snapshots/notebooktools-right-panel-firefox-linux.png
  ui-tests/test/notebook.spec.ts-snapshots/toc-left-panel-chromium-linux.png
  ui-tests/test/notebook.spec.ts-snapshots/toc-left-panel-firefox-linux.png
  ui-tests/test/notebooks/simple_toc.ipynb
  ui-tests/test/smoke.spec.ts
  ui-tests/test/utils.ts
  yarn.lock
Labels: enhancement

#6561 Fix typo in CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#6565 fixed UserMenu alignment
  packages/application-extension/style/base.css
Labels: enhancement

#6566 Update to JupyterLab 4.0.0a30
  .github/actions/build-dist/action.yml
  .github/workflows/buildutils.yml
  .gitignore
  app/index.js
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application-extension/src/index.ts
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/docmanager-extension/src/index.ts
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/notebook-extension/style/base.css
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  ui-tests/package.json
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#6568 Automated Changelog Entry for 7.0.0a7 on main
  CHANGELOG.md
Labels: documentation

#6569 Automated Changelog Entry for 6.5.0 on 6.5.x
  CHANGELOG.md
Labels: documentation

#6571 Automated Changelog Entry for 6.5.1 on 6.5.x
  CHANGELOG.md
Labels: documentation

#6548 Remove the `nbclassic` explicit uninstall on Binder
  binder/postBuild
Labels: maintenance

#6578 Fix: jQuery-UI 404 Error by updating dependency path in static template
  notebook/templates/page.html
Labels: bug

#6581 Maintenance cleanup
  .flake8
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .pre-commit-config.yaml
  .readthedocs.yaml
  CHANGELOG.md
  README.md
  package.json
  pyproject.toml
Labels: maintenance

#6584 Fix PDF renderer
  app/package.json
  packages/application/src/app.ts
Labels: bug

#6586 Add dependabot config to update GitHub Actions
  .github/dependabot.yml
Labels: maintenance

#6580 Ensure custom preload is correctly handled
  docs/environment.yml
  notebook/templates/page.html
  setup.py
  tools/build-main.js
Labels: bug

#6579 Update to lerna 6
  app/package.json
  lerna.json
  package.json
  pyproject.toml
  yarn.lock
Labels: maintenance

#6592 Restyle about dialog
  packages/help-extension/src/index.tsx
  packages/help-extension/style/base.css
Labels: enhancement

#6593 Depend on nbclassic 0.4.7
  docs/environment.yml
  setup.py
Labels: maintenance, dependencies

#6606 Automated Changelog Entry for 6.5.2 on 6.5.x
  CHANGELOG.md
Labels: documentation
