Repository jupyter/notebook, pull requests merged in 2022-11, with the labels that each got.

#6616 Fix async contents handling and add test
  .github/workflows/build.yml
  notebook/app.py
  tests/conftest.py
  tests/test_app.py
Labels: bug

#6608 Explicitly specify favicon for /tree view in Notebook
  notebook/templates/tree.html
Labels: bug

#6625 Moves panel related objects to a dedicated module file
  packages/application-extension/src/index.ts
  packages/application-extension/src/sidebarpalette.ts
  packages/application/src/index.ts
  packages/application/src/panelhandler.ts
  packages/application/src/shell.ts
  ui-tests/test/notebook.spec.ts
  ui-tests/test/smoke.spec.ts
Labels: maintenance

#6627 Update to JupyterLab 4.0.0a31
  .github/workflows/buildutils.yml
  app/index.js
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/notebook-extension/src/index.ts
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  yarn.lock
Labels: enhancement

#6629 Add run-p (npm-run-all) to dev dependencies
  package.json
  yarn.lock
Labels: maintenance

#6635 Clean up workflows
  .github/workflows/build.yml
Labels: maintenance

#6638 use main branch for config
  README.md
Labels: maintenance

#6639 Add more Python tests
  tests/test_app.py
Labels: maintenance

#6640 Update to TypeScript 4.9
  buildutils/package.json
  package.json
  packages/_metapackage/package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  yarn.lock
Labels: maintenance

#6648 Remove PDF link to Jupyter Notebook docs
  README.md
Labels: documentation

#6626 Fix issue template formatting
  .github/ISSUE_TEMPLATE/bug_report.md
  .pre-commit-config.yaml
Labels: maintenance
