Repository jupyter/notebook, pull requests merged in 2022-03, with the labels that each got.

#6303 Remove the custom run keyboard shortcut
  packages/notebook-extension/src/index.ts
Labels: maintenance

#6305 Automated Changelog Entry for 7.0.0a1 on main
  CHANGELOG.md
Labels: documentation

#6306 Update example notebook on Binder
  binder/example.ipynb
Labels: documentation

#6308 Update 6.4.x branch with some missing commits
  CHANGELOG.md
  notebook/services/kernels/handlers.py
  notebook/static/base/js/namespace.js
Labels: maintenance

#6309 Automated Changelog Entry for 6.4.9 on 6.4.x
  CHANGELOG.md
Labels: documentation

#6310 Update links and fix check-release
  .github/workflows/check-release.yml
  CHANGELOG.md
  README.md
  docs-translations/hi-IN/README.md
  docs-translations/ja-JP/README.md
  docs-translations/ko-KR/README.md
  docs-translations/zh-CN/README.md
  docs/doc-requirements.txt
  docs/environment.yml
  docs/source/config_overview.rst
  docs/source/examples/Notebook/examples_index.rst
  docs/source/links.txt
  docs/source/notebook.rst
  docs/source/template.tpl
  notebook/static/notebook/js/notebook.js
  setup.py
Labels: maintenance

#6312 Automated Changelog Entry for 6.4.9 on 6.4.x
  CHANGELOG.md
Labels: documentation

#6313 Minor copy edit in README
  README.md
Labels: enhancement, documentation

#6314 Update to JupyterLab 4.0.0a22
  .github/actions/build-dist/action.yml
  .github/workflows/buildutils.yml
  app/index.js
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/ui-components/package.json
  pyproject.toml
  setup.cfg
  ui-tests/package.json
  ui-tests/test/mobile.spec.ts
  ui-tests/test/mobile.spec.ts-snapshots/notebook-firefox-linux.png
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#6317 docs: fix spelling
  README.md
Labels: documentation

#6318 Fix rendering of markdown
  app/index.js
  app/package.json
  binder/example.ipynb
  yarn.lock
Labels: bug

#6315 Add support for opening a document with a different factory
  packages/application-extension/src/index.ts
  packages/docmanager-extension/src/index.ts
Labels: enhancement

#6323 Automated Changelog Entry for 7.0.0a2 on main
  CHANGELOG.md
Labels: documentation
