Repository jupyter/notebook, pull requests merged in 2022-07, with the labels that each got.

#6464 Fix tests
  pyproject.toml
Labels: maintenance

#6477 Change the tab renderer to allow adding closable tab
  packages/tree-extension/src/index.ts
Labels: enhancement

#6480 Updates README to document maintained versions
  README.md
Labels: enhancement, documentation

#6485 Fix Check Release/link_check CI Job
  CONTRIBUTING.rst
  docs/source/examples/Notebook/Distributing Jupyter Extensions as Python Packages.ipynb
Labels: documentation

#6484 Selenium test updates
  notebook/tests/selenium/test_dashboard_nav.py
  notebook/tests/selenium/test_display_image.py
  notebook/tests/selenium/test_display_isolation.py
  notebook/tests/selenium/test_dualmode_arrows.py
  notebook/tests/selenium/test_execute_code.py
  notebook/tests/selenium/test_interrupt.py
  notebook/tests/selenium/test_kernel_menu.py
  notebook/tests/selenium/test_markdown.py
  notebook/tests/selenium/test_multiselect.py
  notebook/tests/selenium/test_notifications.py
  notebook/tests/selenium/test_prompt_numbers.py
  notebook/tests/selenium/test_save.py
  notebook/tests/selenium/test_save_as_notebook.py
  notebook/tests/selenium/test_save_readonly_as.py
  notebook/tests/selenium/utils.py
Labels: maintenance

#6488 Update contributing docs to reflect changes to build process
  CONTRIBUTING.rst
Labels: documentation

#6490 Automated Changelog Entry for 6.5.0a0 on 6.5.x
  CHANGELOG.md
Labels: documentation

#6471 Bump minimum version of jQuery to 3.6.0
  bower.json
  setup.py
Labels: maintenance

#6493 Automated Changelog Entry for 6.5.0b0 on 6.5.x
  CHANGELOG.md
Labels: documentation
