Repository jupyter/notebook, pull requests merged in 2022-04, with the labels that each got.

#6331 Adopt pre-commit
  .github/workflows/build.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  docs/jsdoc_plugin.js
  lint-staged.config.js
  package.json
  pyproject.toml
  setup.cfg
  setup.py
  tsconfig.eslint.json
  yarn.lock
Labels: maintenance

#6337 Add flake8 and git-blame-ignore-revs
  .git-blame-ignore-revs
  .pre-commit-config.yaml
  docs/source/conf.py
  notebook/__init__.py
  setup.cfg
Labels: maintenance

#6338 Add pytest and handle warnings
  .github/workflows/build.yml
  .github/workflows/docs.yml
  MANIFEST.in
  docs/source/conf.py
  notebook/app.py
  pyproject.toml
  setup.cfg
  tests/conftest.py
  tests/test_app.py
Labels: maintenance

#6345 Update to TypeScript 4.6
  buildutils/package.json
  package.json
  packages/_metapackage/package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/ui-components/package.json
  yarn.lock
Labels: maintenance

#6349 Clean up pre-commit
  .github/workflows/build.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  docs/source/links.txt
  pyproject.toml
Labels: maintenance

#6357 Add testpath to the test dependencies.
  setup.py
Labels: maintenance

#6356 Temporary workaround to fix js-tests related to sanitizer js loading by phantomjs
  .github/workflows/js.yml
  bower.json
  setupbase.py
  tools/security_deprecated.js
Labels: maintenance

#6358 Update further to ipykernel comm refactoring
  notebook/tests/services/kernel.js
  notebook/tests/services/serialize.js
  notebook/tests/services/session.js
Labels: bug

#6362 Automated Changelog Entry for 6.4.10 on 6.4.x
  CHANGELOG.md
Labels: documentation

#6364 Copy edits in config, edits bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation

#6367 Back to 6.4.10 main version, instead of 6.5.0.dev0
  notebook/_version.py
  notebook/static/base/js/namespace.js
  pyproject.toml
Labels: maintenance

#6366 Initialize handler page_config from Server traitlets
  notebook/app.py
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-firefox-linux.png
Labels: enhancement

#6369 Fix build workflow on CI
  .github/workflows/build.yml
  setup.cfg
Labels: maintenance

#6371 Update to JupyterLab 4.0.0a24
  .github/actions/build-dist/action.yml
  .github/workflows/buildutils.yml
  app/index.js
  app/package.json
  buildutils/package.json
  notebook/app.py
  package.json
  packages/application-extension/package.json
  packages/application-extension/schema/menus.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree-extension/style/base.css
  packages/ui-components/package.json
  pyproject.toml
  setup.cfg
  ui-tests/package.json
  ui-tests/test/mobile.spec.ts-snapshots/tree-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/tree-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-firefox-linux.png
  ui-tests/yarn.lock
  yarn.lock
Labels: enhancement

#6374 Add a label to the upload button
  packages/tree-extension/src/index.ts
  ui-tests/test/mobile.spec.ts-snapshots/tree-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/tree-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-firefox-linux.png
Labels: enhancement

#6375 Link to v6 plan in the README
  README.md
Labels: documentation

#6376 Remove blank space at the bottom of the notebook
  packages/notebook-extension/style/base.css
  ui-tests/test/mobile.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-firefox-linux.png
Labels: enhancement

#6377 Show file checkboxes by default in the file browser
  packages/tree-extension/src/index.ts
  ui-tests/test/mobile.spec.ts-snapshots/tree-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/tree-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-firefox-linux.png
Labels: enhancement

#6380 Add UI tests for a simple notebook
  ui-tests/test/general.spec.ts
  ui-tests/test/general.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/general.spec.ts-snapshots/notebook-firefox-linux.png
  ui-tests/test/notebooks/simple.ipynb
Labels: maintenance

#6379 Fix opening JupyterLab from Notebook
  notebook/app.py
  ui-tests/test/smoke.spec.ts
Labels: bug

#6381 Automated Changelog Entry for 7.0.0a3 on main
  CHANGELOG.md
Labels: documentation

#6382 Fix ESLint config for tests
  tsconfig.eslint.json
Labels: maintenance

#6383 Add Visual Regression Test for the export submenu
  ui-tests/test/menus.spec.ts
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-save-and-export-notebook-as…-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-save-and-export-notebook-as…-firefox-linux.png
Labels: maintenance

#6412 Remove the "Appearance" menu entry
  packages/application-extension/schema/menus.json
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-firefox-linux.png
Labels: enhancement
