Repository jupyter/notebook, pull requests merged in 2023-12, with the labels that each got.

#6968 Add the JupyterLab resources plugin
  app/package.json
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-help-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-help-firefox-linux.png
  yarn.lock
Labels: enhancement

#7176 Update publish-release workflow for PyPI trusted publisher
  .github/workflows/publish-release.yml
Labels: maintenance

#7178 Fix toggle functionality for widgets.
  packages/application/src/panelhandler.ts
Labels: enhancement

#7183 [7.0.x] Install stable JupyterLab 4.0 in the releaser hook
  pyproject.toml
Labels: maintenance

#7184 Backport PR #7132 on branch 7.0.x (Adopt ruff format)
  .pre-commit-config.yaml
  notebook/app.py
  pyproject.toml
Labels: maintenance

#7185 Backport PR #7142 on branch 7.0.x (Clean up lint handling)
  .github/workflows/build.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: maintenance

#7186 Backport PR #7145 on branch 7.0.x (Update ruff config and typing)
  .pre-commit-config.yaml
  binder/example.ipynb
  docs/source/examples/Notebook/Running Code.ipynb
  notebook/app.py
  pyproject.toml
  ui-tests/test/notebooks/autoscroll.ipynb
Labels: maintenance

#7179 Backport PR #7176 on branch 7.0.x (Update publish-release workflow for PyPI trusted publisher)
  .github/workflows/publish-release.yml
Labels: maintenance

#6887 Remove viewport workaround in the UI tests
  ui-tests/test/mobile.spec.ts
  ui-tests/test/utils.ts
Labels: maintenance

#7190 Update ruff config
  .pre-commit-config.yaml
  docs/source/conf.py
  notebook/__init__.py
  notebook/_version.py
  notebook/app.py
  pyproject.toml
  tests/conftest.py
  tests/test_app.py
Labels: maintenance

#7193 Clarify README about supported versions (post v7 release)
  README.md
Labels: documentation

#7196 Update to JupyterLab 4.1.0b0
  .github/workflows/buildutils.yml
  .pre-commit-config.yaml
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/notebook-extension/style/base.css
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  yarn.lock
Labels: maintenance

#7197 Add nbviewer.jupyter.org to the ignore list
  .github/workflows/build.yml
  docs/source/examples/Notebook/Notebook Basics.ipynb
Labels: maintenance

#7198 Add the plugin manager
  app/index.template.js
  app/package.json
  packages/application-extension/schema/shell.json
  packages/application/src/app.ts
  yarn.lock
Labels: enhancement
