Repository jupyter/notebook, pull requests merged in 2023-08, with the labels that each got.

#6993 Added documentation link in Help menu
  packages/help-extension/src/index.tsx
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-help-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-help-firefox-linux.png
Labels: enhancement

#6996 Improve about dialog
  packages/help-extension/style/base.css
Labels: enhancement

#6997 Remove `RedirectHandler`
  notebook/app.py
Labels: bug

#6998 Update to JupyterLab 4.0.4 packages
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  yarn.lock
Labels: enhancement

#6965 Fix Python 3.12 compatibility
  tests/conftest.py
Labels: bug

#7001 Mention the nx graph in the contributing guide
  CONTRIBUTING.md
Labels: documentation

#6999 Test against Python 3.12
  .github/workflows/build.yml
Labels: maintenance

#7013 Update to JupyterLab 4.0.5
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-firefox-linux.png
  yarn.lock
Labels: maintenance

#7016 Require importlib_resources for testing on Python < 3.10
  .github/workflows/build.yml
  pyproject.toml
  tests/conftest.py
Labels: bug
