Repository jupyter/notebook, pull requests merged in 2023-01, with the labels that each got.

#6675 Fix `check_links` and and `Test Lint` CI failures
  CHANGELOG.md
  tests/conftest.py
Labels: maintenance

#6679 Update the copyright date to 2023 in the about dialog
  packages/help-extension/src/index.tsx
Labels: maintenance

#6588 Tree view enhancement
  packages/_metapackage/tsconfig.json
  packages/application-extension/src/index.ts
  packages/tree-extension/src/index.ts
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-firefox-linux.png
  ui-tests/test/tree.spec.ts
Labels: enhancement

#6316 Add the Settings Editor to the landing page
  app/index.js
  app/package.json
  packages/tree-extension/package.json
  packages/tree-extension/src/index.ts
  packages/tree/style/base.css
  ui-tests/test/mobile.spec.ts-snapshots/tree-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/tree-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-firefox-linux.png
  yarn.lock
Labels: enhancement

#6695 Add back `# type:ignore`
  tests/conftest.py
Labels: maintenance

#6694 Fix console error when adding a widget to a side panel
  packages/application/src/panelhandler.ts
Labels: bug

#6696 Create `auto_author_assign.yml` workflow
  .github/workflows/auto_author_assign.yml
Labels: maintenance

#6698 Add releaser workflows
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  RELEASE.md
Labels: maintenance

#6700 Help-extension split into multiple plugins
  packages/help-extension/schema/open.json
  packages/help-extension/src/index.tsx
Labels: maintenance

#6705 Reintroduce desktop file
  jupyter-notebook.desktop
  pyproject.toml
Labels: maintenance
