Repository jupyter/notebook, pull requests merged in 2023-07, with the labels that each got.

#6964 fix: update link to troubleshooting guidelines
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation

#6967 Update to JupyterLab 4.0.3
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  yarn.lock
Labels: maintenance

#6961 Update Jupytext Notebook url path
  packages/docmanager-extension/src/index.ts
Labels: bug, tag:Feature Parity

#6971 Fix hatch version when going from rc
  buildutils/src/release-bump.ts
Labels: maintenance

#6972 The future is now
  README.md
Labels: documentation

#6973 Fix link in `README.md`
  README.md
Labels: documentation

#6979 Bump `word-wrap` and `semver`
  yarn.lock
Labels: maintenance

#6982 Update accessibly compliance section in the docs
  docs/source/notebook_7_features.md
Labels: enhancement, documentation

#6980 Update the browser tab favicon on kernel busy
  packages/notebook-extension/src/index.ts
Labels: enhancement

#6749 Pin jupyter_client<8 and pyzmq<25
  setup.py
Labels: bug

#6767 Enable lerna caching for build scripts
  .gitpod.yml
  CONTRIBUTING.md
  app/package.json
  lerna.json
  nx.json
  package.json
  packages/docmanager-extension/package.json
  packages/docmanager-extension/tsconfig.json
  packages/lab-extension/package.json
  yarn.lock
Labels: maintenance
