Repository jupyter/notebook, pull requests merged in 2023-06, with the labels that each got.

#6893 Enhancement: Added drop shadows to markdown, text, and tree views
  packages/application/style/base.css
  packages/notebook-extension/style/base.css
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-firefox-linux.png
Labels: enhancement

#6896 Add `JSONLicenseWebpackPlugin`
  app/webpack.config.js
Labels: maintenance

#6899 Configurable `default_url` for JupyterNotebookApp
  notebook/app.py
Labels: enhancement

#6900 Add the notification plugin
  app/package.json
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-firefox-linux.png
Labels: enhancement

#6866 Add option to open a notebook in NbClassic if it is installed; show "Open in..." dropdown menu if there are multiple options, show single button otherwise
  notebook/app.py
  packages/lab-extension/schema/interface-switcher.json
  packages/lab-extension/src/index.ts
  packages/lab-extension/style/base.css
  ui-tests/test/general.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/general.spec.ts-snapshots/notebook-firefox-linux.png
  ui-tests/test/menus.spec.ts
  ui-tests/test/mobile.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-firefox-linux.png
Labels: enhancement

#6911 Add an empty splash screen on notebook launch to avoid a flash of unstyled content
  packages/application-extension/src/index.ts
Labels: bug

#6841 Load custom CSS
  docs/source/config_overview.md
  notebook/app.py
  notebook/custom/custom.css
  notebook/templates/consoles.html
  notebook/templates/notebooks.html
  notebook/templates/terminals.html
  notebook/templates/tree.html
Labels: enhancement

#6909 Document how to manage plugins and extensions
  docs/source/configuration.md
  docs/source/configuring/config_overview.md
  docs/source/configuring/plugins.md
Labels: documentation

#6913 Rename browser tab title to Home
  notebook/templates/tree.html
  tests/test_app.py
Labels: enhancement

#6905 Fix for "find searches only part of the file" bug
  docs/source/notebook.md
  packages/documentsearch-extension/schema/notebookShellWidgetListener.json
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-edit-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-edit-firefox-linux.png
Labels: bug

#6919 Added example of custom css files
  docs/source/custom_css.md
  docs/source/user-documentation.md
Labels: documentation

#6918 Align JupyterHub config with JupyterLab
  notebook/app.py
Labels: bug

#6922 Update JupyterLab, audit document viewers
  .github/workflows/buildutils.yml
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  yarn.lock
Labels: enhancement

#6923 Fix default viewers override
  packages/application-extension/src/index.ts
Labels: bug

#6938 Make jupyter logo select properly (#6927)
  packages/application-extension/src/index.ts
  packages/application-extension/style/base.css
Labels: bug, tag:Accessibility

#6917 Docs parity for find with JupyterLab.
  docs/source/notebook.md
Labels: documentation

#6939 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#6937 Close the browser tab when clicking on "Close and Shut Down Notebook"
  packages/application-extension/schema/menus.json
  packages/notebook-extension/src/index.ts
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-firefox-linux.png
  ui-tests/test/notebook.spec.ts
Labels: enhancement

#6941 Fix the redirect handler
  notebook/app.py
Labels: bug

#6943 Fix handling of the base url
  notebook/app.py
Labels: bug

#6946 Fix opening files from the CLI
  notebook/app.py
Labels: bug
