Repository jupyter/notebook, pull requests merged in 2023-10, with the labels that each got.

#7082 Fix traitlets typing
  notebook/app.py
Labels: maintenance

#7086 React to the galata update comment
  .github/workflows/playwright-update.yml
Labels: maintenance

#7085 Switch from `hub` to `gh` in the Playwright snapshots update workflow
  .github/workflows/playwright-update.yml
Labels: maintenance

#7094 Remove link to the PDF documentation
  README.md
Labels: maintenance

#7098 Ignore yarn.lock for codespell
  .pre-commit-config.yaml
Labels: maintenance

#7104 Fix typings check on CI
  notebook/app.py
Labels: maintenance

#7105 Update `permissions` in the galata snapshot workflow
  .github/workflows/playwright-update.yml
Labels: maintenance

#7103 Update to JupyterLab 4.0.7
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  ui-tests/test/mobile.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-firefox-linux.png
  yarn.lock
Labels: enhancement

#7110 Fix typings
  notebook/app.py
  yarn.lock
Labels: maintenance

#7109 Updated fav-icon Base URL from JupyterLab PageConfig.
  packages/notebook-extension/src/index.ts
Labels: bug

#7111 Add Python 3.12 classifier
  pyproject.toml
Labels: maintenance

#7129 Set `navigation_with_keys` to `False`
  docs/source/conf.py
Labels: documentation

#7124 Updated ui-tests Configuration in Contributing.md
  CONTRIBUTING.md
Labels: documentation

#7127 Added Lumino Plugin Description (#7008)
  packages/application-extension/src/index.ts
  packages/console-extension/src/index.ts
  packages/docmanager-extension/src/index.ts
  packages/documentsearch-extension/src/index.ts
  packages/help-extension/src/index.tsx
  packages/lab-extension/src/index.ts
  packages/notebook-extension/src/index.ts
  packages/terminal-extension/src/index.ts
  packages/tree-extension/src/index.ts
Labels: enhancement

#7096 Update to JupyterLab 4.1
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  ui-tests/test/mobile.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-firefox-linux.png
  yarn.lock
Labels: enhancement

#7131 Fix python bumping to `minor`
  buildutils/src/release-bump.ts
Labels: maintenance

#7132 Adopt ruff format
  .pre-commit-config.yaml
  notebook/app.py
  pyproject.toml
Labels: maintenance
