Repository jupyter/notebook, pull requests merged in 2023-03, with the labels that each got.

#6760 Automated Changelog Entry for 6.5.3 on 6.5.x
  CHANGELOG.md
Labels: documentation

#6757 Update to JupyterLab 4.0.0a35
  .gitpod.yml
  app/package.json
  buildutils/package.json
  buildutils/src/ensure-repo.ts
  package.json
  packages/_metapackage/package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/lab-extension/src/index.ts
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree-extension/schema/widget.json
  packages/tree-extension/src/index.ts
  packages/tree-extension/style/base.css
  packages/tree/package.json
  packages/ui-components/package.json
  tsconfigbase.json
  tsconfigbase.test.json
  ui-tests/test/general.spec.ts-snapshots/notebook-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-settings-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-settings-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-firefox-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-firefox-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/tree-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/tree-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-firefox-linux.png
  yarn.lock
Labels: enhancement

#6764 Remove empty `py.test` file
  notebook/py.test
Labels: maintenance

#6766 Clean up interface switcher plugin in preparation for release
  packages/lab-extension/package.json
  packages/lab-extension/src/index.ts
  packages/lab-extension/style/base.css
  packages/tree-extension/style/base.css
  ui-tests/test/general.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/general.spec.ts-snapshots/notebook-firefox-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-firefox-linux.png
Labels: maintenance

#6770 Convert docs to Markdown
  docs/source/config_overview.md
  docs/source/config_overview.rst
  docs/source/configuration.md
  docs/source/configuration.rst
  docs/source/contributor.md
  docs/source/contributor.rst
  docs/source/development_faq.md
  docs/source/development_faq.rst
  docs/source/extending/frontend_extensions.md
  docs/source/extending/index.md
  docs/source/extending/index.rst
  docs/source/index.md
  docs/source/index.rst
  docs/source/migrate_to_notebook7.md
  docs/source/notebook.md
  docs/source/troubleshooting.md
  docs/source/troubleshooting.rst
  docs/source/ui_components.md
  docs/source/user-documentation.md
  docs/source/user-documentation.rst
Labels: documentation

#6771 Add documentation for contributing to the docs
  .gitpod.yml
  CONTRIBUTING.md
  README.md
  pyproject.toml
Labels: documentation

#6773 Update to JupyterLab 4.0.0a36
  .github/workflows/buildutils.yml
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  ui-tests/test/general.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/general.spec.ts-snapshots/notebook-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-edit-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-edit-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-run-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-run-firefox-linux.png
  ui-tests/test/notebook.spec.ts-snapshots/notebooktools-right-panel-chromium-linux.png
  ui-tests/test/notebook.spec.ts-snapshots/notebooktools-right-panel-firefox-linux.png
  yarn.lock
Labels: enhancement

#6775 Replace the use of `toArray` by `Array.from`
  packages/notebook-extension/src/trusted.tsx
Labels: maintenance

#6777 Update to JupyterLab 4.0.0a37
  .eslintrc.js
  .github/workflows/buildutils.yml
  .github/workflows/playwright-update.yml
  .github/workflows/ui-tests.yml
  .gitignore
  .gitpod.yml
  .yarnrc.yml
  app/package.json
  app/webpack.config.js
  app/webpack.config.watch.js
  buildutils/package.json
  buildutils/src/develop.ts
  buildutils/src/ensure-repo.ts
  docs/jsdoc_plugin.js
  lerna.json
  package.json
  packages/_metapackage/package.json
  packages/application-extension/package.json
  packages/application-extension/src/index.ts
  packages/application/jest.config.js
  packages/application/package.json
  packages/application/src/app.ts
  packages/application/src/panelhandler.ts
  packages/application/src/shell.ts
  packages/application/test/shell.spec.ts
  packages/console-extension/package.json
  packages/console-extension/src/index.ts
  packages/docmanager-extension/package.json
  packages/docmanager-extension/src/index.ts
  packages/documentsearch-extension/package.json
  packages/documentsearch-extension/src/index.ts
  packages/help-extension/package.json
  packages/help-extension/src/index.tsx
  packages/lab-extension/package.json
  packages/lab-extension/src/index.ts
  packages/notebook-extension/package.json
  packages/notebook-extension/src/index.ts
  packages/notebook-extension/src/trusted.tsx
  packages/terminal-extension/package.json
  packages/terminal-extension/src/index.ts
  packages/tree-extension/package.json
  packages/tree-extension/src/index.ts
  packages/tree/package.json
  packages/tree/src/notebook-tree.ts
  packages/ui-components/package.json
  packages/ui-components/src/icon/iconimports.ts
  pyproject.toml
  ui-tests/package.json
  ui-tests/playwright.config.ts
  ui-tests/test/editor.spec.ts
  ui-tests/test/fixtures.ts
  ui-tests/test/general.spec.ts
  ui-tests/test/menus.spec.ts
  ui-tests/test/mobile.spec.ts
  ui-tests/test/notebook.spec.ts
  ui-tests/test/settings.spec.ts
  ui-tests/test/smoke.spec.ts
  ui-tests/test/tree.spec.ts
  ui-tests/yarn.lock
  yarn.lock
Labels: enhancement

#6795 Fix JSON setting editor not opening issue
  app/package.json
  packages/tree-extension/src/index.ts
Labels: enhancement

#6804 added white space to bottom of edit files
  notebook/templates/edit.html
  packages/application/src/shell.ts
  packages/application/style/base.css
Labels: bug

#6808 Add show_banner trait to control the banner display
  docs/source/frontend_config.rst
  notebook/base/handlers.py
  notebook/notebookapp.py
  notebook/templates/page.html
Labels: enhancement
