Repository jupyter/notebook, pull requests merged in 2023-09, with the labels that each got.

#7026 Fix docs build on Gitpod
  .gitpod.yml
Labels: maintenance

#7037 Add `datetime.datetime.utc()` to the filter list
  pyproject.toml
Labels: maintenance

#7036 fix trusted status indication
  packages/notebook-extension/src/trusted.tsx
  ui-tests/test/general.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/general.spec.ts-snapshots/notebook-firefox-linux.png
Labels: bug

#7039 Adopt sp-repo-review
  .github/actions/build-dist/action.yml
  .github/dependabot.yml
  .github/jupyterlab-probot.yml
  .github/workflows/build.yml
  .github/workflows/buildutils.yml
  .github/workflows/check-release.yml
  .github/workflows/lock.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/ui-tests.yml
  .pre-commit-config.yaml
  .readthedocs.yaml
  CHANGELOG.md
  README.md
  binder/environment.yml
  docs/source/migrating/multiple-interfaces.md
  notebook/__init__.py
  notebook/__main__.py
  notebook/_version.py
  notebook/app.py
  packages/application-extension/src/index.ts
  packages/application/src/app.ts
  packages/application/src/panelhandler.ts
  packages/notebook-extension/src/trusted.tsx
  packages/notebook-extension/style/base.css
  packages/tree-extension/src/fileactions.tsx
  pyproject.toml
Labels: maintenance

#7049 Update to JupyterLab 4.0.6
  app/package.json
  buildutils/package.json
  notebook/app.py
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  ui-tests/test/jupyter_server_config.py
  yarn.lock
Labels: enhancement

#7050 Enable the Playwright trace
  ui-tests/playwright.config.ts
Labels: maintenance

#7058 Add `deduplicate` top-level script
  package.json
Labels: maintenance

#7051 fix traitlets warning->error on 6.5.x
  notebook/notebookapp.py
  notebook/traittypes.py
Labels: bug

#7059 Update Binder environment
  binder/environment.yml
Labels: maintenance

#7056 Move opening path in new browser tabs to a separate plugin
  binder/environment.yml
  binder/postBuild
  packages/application-extension/src/index.ts
  packages/application-extension/tsconfig.json
  packages/application/src/index.ts
  packages/application/src/pathopener.ts
  packages/application/src/tokens.ts
  packages/console-extension/package.json
  packages/console-extension/src/index.ts
  packages/console-extension/tsconfig.json
  packages/docmanager-extension/src/index.ts
  packages/help-extension/tsconfig.json
  packages/lab-extension/src/index.ts
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/terminal-extension/src/index.ts
  packages/terminal-extension/tsconfig.json
  pyproject.toml
  yarn.lock
Labels: maintenance

#7061 Fix `app_version`
  notebook/app.py
Labels: bug

#7070 ci: set minimal permissions to workflows
  .github/workflows/auto_author_assign.yml
  .github/workflows/binder.yml
  .github/workflows/build.yml
  .github/workflows/buildutils.yml
  .github/workflows/check-release.yml
  .github/workflows/enforce-label.yml
  .github/workflows/lock.yml
  .github/workflows/playwright-update.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/ui-tests.yml
Labels: maintenance

#7074 Improve docs setup (SVG logos, repo links)
  docs/source/_static/jupyter_logo.svg
  docs/source/_static/logo-rectangle-dark.svg
  docs/source/_static/logo-rectangle.svg
  docs/source/conf.py
  docs/source/custom_css.md
Labels: documentation
