Repository jupyter/notebook, pull requests merged in 2023-04, with the labels that each got.

#6812 fix typo in the migration guide
  docs/source/migrate_to_notebook7.md
Labels: documentation

#6816 Add missing singleton packages for RTC
  app/package.json
  buildutils/src/ensure-repo.ts
  docs/source/notebook_7_features.md
Labels: maintenance

#6829 Use correct canonical URL while building docs
  docs/source/conf.py
Labels: documentation

#6834 Fixes the notebooktools
  app/package.json
  ui-tests/test/notebook.spec.ts-snapshots/notebooktools-right-panel-chromium-linux.png
  ui-tests/test/notebook.spec.ts-snapshots/notebooktools-right-panel-firefox-linux.png
  ui-tests/test/notebooks/simple.ipynb
  yarn.lock
Labels: bug

#6835 Automated Changelog Entry for 6.5.4 on 6.5.x
  CHANGELOG.md
Labels: documentation

#6839 Use local coverage
  .github/workflows/build.yml
  README.md
  codecov.yml
  pyproject.toml
Labels: maintenance

#6840 fix import of warnings.warn
  .github/workflows/docs.yml
  .github/workflows/python.yml
  notebook/traittypes.py
Labels: bug

#6838 Update to JupyterLab `4.0.0b1` and `4.0.0b2`
  .github/workflows/buildutils.yml
  app/package.json
  app/webpack.config.js
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/help-extension/schema/open.json
  packages/help-extension/src/index.tsx
  packages/help-extension/style/base.css
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/notebook-extension/style/base.css
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  ui-tests/package.json
  ui-tests/test/general.spec.ts
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-help-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-help-firefox-linux.png
  ui-tests/yarn.lock
  yarn.lock
Labels: enhancement

#6850 Added extra information and user-action summaries to 7 migration docs.
  docs/source/migrate_to_notebook7.md
Labels: documentation

#6853 Update to JupyterLab 4.0.0rc0
  .github/workflows/build.yml
  .github/workflows/buildutils.yml
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  ui-tests/package.json
  ui-tests/yarn.lock
  yarn.lock
Labels: enhancement
