Repository jupyter/notebook, pull requests merged in 2023-05, with the labels that each got.

#6836 Fix top bar visibility not picking up settings overrides (#6833)
  packages/application-extension/schema/top.json
  packages/application-extension/src/index.ts
Labels: bug

#6844 Add Skip Link to Notebook
  packages/application/src/shell.ts
  packages/application/test/shell.spec.ts
  packages/notebook-extension/style/base.css
Labels: enhancement

#6847 Change "Interface" menu to "Open in...", shorten names of menu items inside
  packages/lab-extension/schema/interface-switcher.json
  packages/lab-extension/src/index.ts
  ui-tests/test/general.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/general.spec.ts-snapshots/notebook-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-firefox-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-firefox-linux.png
Labels: enhancement

#6861 Update RTD image
  .readthedocs.yaml
  pyproject.toml
Labels: maintenance

#6864 Update to JupyterLab 4.0.0rc1
  .github/workflows/buildutils.yml
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  ui-tests/package.json
  ui-tests/yarn.lock
  yarn.lock
Labels: enhancement

#6870 Fix check links on CI
  CHANGELOG.md
Labels: maintenance

#6843 Remove "Close Tab" menu entry
  packages/application-extension/schema/menus.json
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-firefox-linux.png
Labels: enhancement

#6871 Update to JupyterLab 4 final
  .github/workflows/buildutils.yml
  app/package.json
  app/style.js
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  ui-tests/package.json
  yarn.lock
Labels: enhancement

#6873 Fix handling of the default factory in the URL
  packages/docmanager-extension/src/index.ts
Labels: bug

#6874 Update to Playwright 1.33
  ui-tests/package.json
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-edit-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-new-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-save-and-export-notebook-as…-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-help-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-kernel-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-run-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-settings-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-settings-theme-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-firefox-linux.png
  ui-tests/yarn.lock
Labels: maintenance

#6872 Enable add a cell button
  packages/notebook-extension/style/base.css
  ui-tests/test/general.spec.ts
  ui-tests/test/mobile.spec.ts
  ui-tests/test/utils.ts
Labels: enhancement

#6879 Copy edits for `migrate_to_notebook7`
  docs/source/migrate_to_notebook7.md
Labels: enhancement, documentation

#6880 Fix playwright bot
  .github/workflows/playwright-update.yml
  ui-tests/playwright.config.ts
Labels: maintenance, tag:Testing

#6885 Provide a custom rendermime plugin to handle local links
  .github/workflows/build.yml
  app/package.json
  packages/application-extension/package.json
  packages/application-extension/src/index.ts
  ui-tests/test/links.spec.ts
  ui-tests/test/notebooks/local_links.ipynb
  yarn.lock
Labels: bug

#6888 Add file browser actions to the file browser toolbar
  packages/tree-extension/schema/file-actions.json
  packages/tree-extension/src/fileactions.tsx
  packages/tree-extension/src/index.ts
  packages/tree-extension/style/base.css
  ui-tests/test/filebrowser.spec.ts
  ui-tests/test/mobile.spec.ts-snapshots/tree-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/tree-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-firefox-linux.png
Labels: enhancement

#6892 Update to JupyterLab 4.0.1
  .github/workflows/buildutils.yml
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree-extension/src/index.ts
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  yarn.lock
Labels: enhancement

#6894 Simplify Gitpod setup
  .gitpod.yml
Labels: maintenance

#6877 Jupyter Notebook ecosystem docs improvements
  docs/source/index.md
  docs/source/notebook.md
  docs/source/user-documentation.md
Labels: documentation
