Repository jupyter/notebook, pull requests merged in 2023-02, with the labels that each got.

#6706 Add more lint checks
  .pre-commit-config.yaml
  pyproject.toml
Labels: maintenance

#6713 Update to JupyterLab 4.0.0a33
  .github/workflows/build.yml
  .github/workflows/buildutils.yml
  app/index.js
  app/package.json
  buildutils/package.json
  notebook/app.py
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree-extension/src/index.ts
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  ui-tests/test/general.spec.ts
  ui-tests/test/general.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/general.spec.ts-snapshots/notebook-firefox-linux.png
  yarn.lock
Labels: enhancement

#6719 Resolving some accessibility issues
  packages/application/src/panelhandler.ts
  packages/application/src/shell.ts
  packages/notebook-extension/src/index.ts
  packages/tree-extension/src/index.ts
  ui-tests/test/tree.spec.ts
Labels: enhancement

#6723 Add workflow to update snapshots
  .github/workflows/playwright-update.yml
Labels: maintenance

#6724 Fix Playwright snapshot update workflow
  .github/workflows/playwright-update.yml
Labels: maintenance

#6731 Hide the debugger button on mobile
  packages/notebook-extension/style/base.css
  ui-tests/test/mobile.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-chromium-linux.png
Labels: enhancement

#6732 Update to JupyterLab 4.0.0a34
  .github/workflows/buildutils.yml
  app/index.js
  app/package.json
  buildutils/package.json
  jupyter_config.json
  notebook/app.py
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  ui-tests/package.json
  ui-tests/test/jupyter_server_config.py
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-edit-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-edit-firefox-linux.png
  ui-tests/yarn.lock
  yarn.lock
Labels: enhancement

#6733 Add section about updating reference snapshots
  CONTRIBUTING.md
Labels: documentation

#6718 Enable `nx`
  .github/workflows/check-release.yml
  app/package.json
  buildutils/package.json
  lerna.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
Labels: maintenance

#6736 Add trusted indicator
  packages/notebook-extension/src/index.ts
  packages/notebook-extension/src/trusted.tsx
  packages/notebook-extension/style/base.css
  ui-tests/test/general.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/general.spec.ts-snapshots/notebook-firefox-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-firefox-linux.png
Labels: enhancement

#6737 Docs: add migrate to notebook7 page
  docs/source/index.rst
  docs/source/migrate_to_notebook7.rst
Labels: documentation

#6741 Corrected "Recomment" to "Recommend"
  CONTRIBUTING.md
Labels: documentation

#6738 File browser CSS tweaks
  packages/application/style/base.css
  packages/tree-extension/src/index.ts
  packages/tree-extension/style/base.css
  packages/tree-extension/style/index.css
  packages/tree-extension/style/index.js
  packages/tree/style/base.css
  ui-tests/test/mobile.spec.ts-snapshots/tree-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/tree-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-firefox-linux.png
Labels: enhancement

#6735 Update to TypeScript 5
  buildutils/package.json
  package.json
  packages/_metapackage/package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  yarn.lock
Labels: maintenance

#6742 Add a banner and log to information about the migration to Notebook 7 plan
  notebook/notebookapp.py
  notebook/templates/page.html
Labels: enhancement

#6743 Clean up license
  LICENSE
  README.md
Labels: maintenance

#6750 Fix loading of plugins
  .eslintignore
  .prettierignore
  app/index.js
  app/index.template.js
  app/package.json
  app/webpack.config.js
  packages/tree-extension/src/index.ts
Labels: enhancement

#6747 Add the extension manager
  app/package.json
  yarn.lock
Labels: enhancement
