Repository jupyter/notebook, pull requests merged in 2024-02, with the labels that each got.

#7230 Update to JupyterLab 4.1.0rc1
  .github/workflows/buildutils.yml
  .pre-commit-config.yaml
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  yarn.lock
Labels: maintenance

#7232 Add user facing changelog for 7.1
  CHANGELOG.md
Labels: documentation

#7236 Backport PR #7235 on branch 7.0.x (Fix link in `CONTRIBUTING.md`)
  CONTRIBUTING.md
Labels: documentation

#7234 Update to JupyterLab 4.1.0 final
  .github/workflows/buildutils.yml
  .pre-commit-config.yaml
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  yarn.lock
Labels: maintenance

#7099 Added Edit Notebook Metadata Option (#6402)
  packages/notebook-extension/schema/edit-notebook-metadata.json
  packages/notebook-extension/src/index.ts
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-edit-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-edit-firefox-linux.png
Labels: enhancement

#7244 Add documentation for updating `notebook` imports
  docs/source/configuring/config_overview.md
  docs/source/migrate_to_notebook7.md
  docs/source/migrating/server-imports.md
Labels: documentation

#7245 Backport PR #7244 on branch 7.0.x (Add documentation for updating `notebook` imports)
  docs/source/configuring/config_overview.md
  docs/source/migrate_to_notebook7.md
  docs/source/migrating/server-imports.md
Labels: documentation

#7249 Add upper bound on `jupyterlab<4.1`
  .github/workflows/buildutils.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: maintenance

#7250 Follow JupyterLab minor versions
  .github/workflows/buildutils.yml
  .pre-commit-config.yaml
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  yarn.lock
Labels: maintenance

#7255 Create a new notebook with a specific kernel from the new dropdown
  packages/docmanager-extension/src/index.ts
  packages/tree-extension/src/index.ts
  ui-tests/test/mobile.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-firefox-linux.png
  ui-tests/test/smoke.spec.ts
Labels: enhancement, tag:Feature Parity

#7256 Update to JupyterLab 4.1.1
  .github/workflows/buildutils.yml
  .pre-commit-config.yaml
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  yarn.lock
Labels: maintenance

#7258 Fix spurious kernel selection dialog on notebook creation
  packages/docmanager-extension/src/index.ts
  ui-tests/test/mobile.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-firefox-linux.png
Labels: bug

#7265 Grayout "Edit Notebook Metadata" for other file formats.
  packages/notebook-extension/src/index.ts
Labels: bug

#7274 Ignore stackoverflow link
  .github/workflows/build.yml
Labels: maintenance

#7277 Update to JupyterLab 4.1.2 packages
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  yarn.lock
Labels: maintenance
