Repository jupyter/notebook, pull requests merged in 2024-01, with the labels that each got.

#7215 Update to JupyterLab 4.0.11
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  yarn.lock
Labels: enhancement

#7219 Fix `check_links` on CI
  CHANGELOG.md
Labels: maintenance

#7220 Backport PR #7219 on branch 7.0.x (Fix `check_links` on CI)
  CHANGELOG.md
Labels: maintenance

#7222 Update to JupyterLab 4.1.0b2
  .github/workflows/buildutils.yml
  .pre-commit-config.yaml
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application-extension/style/base.css
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  ui-tests/package.json
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#7224 Workaround for the file browser tracker focus issue
  packages/tree-extension/src/index.ts
Labels: bug

#7227 Update to JupyterLab 4.1.0rc0
  .github/workflows/buildutils.yml
  .pre-commit-config.yaml
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  ui-tests/package.json
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance
