Repository jupyter/notebook, pull requests merged in 2024-10, with the labels that each got.

#7472 Fix typos
  CHANGELOG.md
  docs/source/migrating/custom-themes.md
Labels: documentation

#7423 Update to JupyterLab `4.3.0rc0`
  .github/workflows/buildutils.yml
  .pre-commit-config.yaml
  app/package.json
  buildutils/package.json
  notebook/templates/consoles.html
  notebook/templates/edit.html
  notebook/templates/error.html
  notebook/templates/notebooks.html
  notebook/templates/terminals.html
  notebook/templates/tree.html
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/application/style/base.css
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree-extension/schema/widget.json
  packages/tree-extension/src/index.ts
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  tsconfigbase.json
  ui-tests/package.json
  ui-tests/test/general.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/general.spec.ts-snapshots/notebook-firefox-linux.png
  ui-tests/test/layout.spec.ts-snapshots/debugger-chromium-linux.png
  ui-tests/test/layout.spec.ts-snapshots/debugger-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-edit-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-chromium-linux.png
  ui-tests/test/mobile.spec.ts
  ui-tests/test/mobile.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-firefox-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/tree-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/tree-firefox-linux.png
  ui-tests/test/notebook.spec.ts-snapshots/toc-left-panel-chromium-linux.png
  ui-tests/test/notebook.spec.ts-snapshots/toc-left-panel-firefox-linux.png
  ui-tests/test/settings.spec.ts
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-firefox-linux.png
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#7477 Remove the `StateDB` file browser trick
  packages/tree-extension/src/index.ts
Labels: maintenance

#7479 Add the file filter button to the file browser toolbar
  packages/tree-extension/schema/widget.json
  packages/tree-extension/src/index.ts
  packages/tree-extension/style/base.css
  ui-tests/test/mobile.spec.ts
  ui-tests/test/mobile.spec.ts-snapshots/tree-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/tree-firefox-linux.png
  ui-tests/test/settings.spec.ts
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-firefox-linux.png
Labels: enhancement

#7487 Add a setting to enable the notebook to take up the full width
  packages/notebook-extension/schema/full-width-notebook.json
  packages/notebook-extension/src/index.ts
  packages/notebook-extension/style/base.css
  ui-tests/test/general.spec.ts
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-firefox-linux.png
  ui-tests/test/notebook.spec.ts
  ui-tests/test/notebook.spec.ts-snapshots/notebook-full-width-chromium-linux.png
  ui-tests/test/notebook.spec.ts-snapshots/notebook-full-width-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-chromium-linux.png
  ui-tests/test/utils.ts
Labels: enhancement

#7497 Update to JupyterLab `4.3.0rc1`
  .github/workflows/buildutils.yml
  .pre-commit-config.yaml
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  ui-tests/package.json
  ui-tests/test/mobile.spec.ts-snapshots/tree-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-firefox-linux.png
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#7494 Add user facing changelog for `7.3.0`
  CHANGELOG.md
Labels: documentation

#7481 Move handling of the file browser settings to a separate plugin, enable file browser single click navigation
  CHANGELOG.md
  app/package.json
  packages/tree-extension/src/index.ts
  ui-tests/test/filebrowser.spec.ts
Labels: bug

#7508 Rename some header links to fit better
  docs/source/conf.py
  docs/source/contributor.md
  docs/source/migrate_to_notebook7.md
  docs/source/user-documentation.md
Labels: documentation

#7511 Fix for auto scroll output option
  packages/notebook-extension/src/index.ts
Labels: enhancement
