Repository jupyter/notebook, pull requests merged in 2024-05, with the labels that each got.

#7333 Update to JupyterLab 4.2.0rc0
  .github/workflows/buildutils.yml
  .pre-commit-config.yaml
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/notebook-extension/style/base.css
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  ui-tests/package.json
  ui-tests/test/general.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/general.spec.ts-snapshots/notebook-firefox-linux.png
  ui-tests/test/menus.spec.ts
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-edit-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-edit-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-save-and-export-notebook-as-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-save-and-export-notebook-as-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-help-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-help-firefox-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-firefox-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/tree-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/tree-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-firefox-linux.png
  ui-tests/yarn.lock
  yarn.lock
Labels: enhancement

#7299 update RISE extension installation instructions
  docs/source/notebook_7_features.md
Labels: documentation

#7353 Add the `@jupyterlab/notebook-extension:copy-output` plugin
  app/package.json
Labels: bug

#7357 Update to JupyterLab 4.2.0
  .github/workflows/buildutils.yml
  .pre-commit-config.yaml
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  ui-tests/test/mobile.spec.ts-snapshots/notebook-firefox-linux.png
  yarn.lock
Labels: enhancement

#7321 Default to the `full` windowing mode
  packages/notebook-extension/src/index.ts
  packages/notebook-extension/style/base.css
  ui-tests/test/general.spec.ts
  ui-tests/test/general.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/general.spec.ts-snapshots/notebook-firefox-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-firefox-linux.png
Labels: bug

#7363 Fix emoji in create issue screen
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation, maintenance

#7361 Update `@jupyterlab/galata`
  .pre-commit-config.yaml
  ui-tests/package.json
  ui-tests/test/editor.spec.ts
  ui-tests/test/filebrowser.spec.ts
  ui-tests/test/general.spec.ts
  ui-tests/test/layout.spec.ts
  ui-tests/test/links.spec.ts
  ui-tests/test/menus.spec.ts
  ui-tests/test/mobile.spec.ts
  ui-tests/test/mobile.spec.ts-snapshots/notebook-firefox-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/tree-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/tree-firefox-linux.png
  ui-tests/test/notebook.spec.ts
  ui-tests/test/settings.spec.ts
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-firefox-linux.png
  ui-tests/test/smoke.spec.ts
  ui-tests/test/tree.spec.ts
  ui-tests/test/utils.ts
  ui-tests/yarn.lock
Labels: maintenance

#7372 Add user facing changelog for 7.2
  CHANGELOG.md
Labels: documentation

#7374 Duplicate notebook menu option
  packages/application-extension/schema/menus.json
  packages/application-extension/src/index.ts
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-firefox-linux.png
Labels: enhancement

#7378 Update to JupyterLab 4.3.0a0
  .github/workflows/buildutils.yml
  .pre-commit-config.yaml
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  pyproject.toml
  yarn.lock
Labels: maintenance

#7382 Adds message about building code before running 'develop'
  CONTRIBUTING.md
Labels: bug, documentation

#7384 "Close and Shut Down Notebook" shuts down without the confirmation dialog
  packages/notebook-extension/src/index.ts
Labels: bug

#7385 Add missing "Open..." file menu
  packages/notebook-extension/schema/edit-notebook-metadata.json
  packages/notebook-extension/src/index.ts
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-firefox-linux.png
Labels: enhancement
