Repository jupyter/notebook, pull requests merged in 2025-08, with the labels that each got.

#7691 Pin `httpx`
  pyproject.toml
Labels: maintenance

#7689 Update to JupyterLab v4.4.5
  .pre-commit-config.yaml
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree/package.json
  packages/ui-components/package.json
  pixi.lock
  pyproject.toml
  ui-tests/package.json
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#7698 Fix open file with “#” in the filename
  packages/application/src/pathopener.ts
Labels: bug

#7699 Backport PR #7698 on branch 7.4.x (Fix open file with “#” in the filename)
  packages/application/src/pathopener.ts
Labels: bug

#7710 Handle file rename errors
  packages/application-extension/src/index.ts
Labels: bug

#7712 Backport PR #7710 on branch 7.4.x (Handle file rename errors)
  packages/application-extension/src/index.ts
Labels: bug

#7711 Increase the checkpoint polling interval to 30s
  packages/notebook-extension/schema/checkpoints.json
  packages/notebook-extension/src/index.ts
Labels: enhancement

#7709 Define `O` as the keyboard shortcut to toggle cell outputs
  packages/application-extension/schema/shortcuts.json
  packages/application-extension/src/index.ts
  ui-tests/test/notebook.spec.ts
Labels: enhancement, tag:Feature Parity
